### ISSUE TITLE
When I encode wiith this tools,it always error

### ISSUE THREAD

**Issue by Mr-sh11** [dreamtimescape/png_sneak#1]
Traceback (most recent call last):
  File "png_sneak_encode.py", line 439, in <module>
    main()
  File "png_sneak_encode.py", line 387, in main
    png.register_extra_filter(adapt_stego, "stego")
AttributeError: module 'png' has no attribute 'register_extra_filter'

**Comment by dreamtimescape** [comment]
This is most likely due to the wrong png package being used.
It is required to use the purepng package instead of the default png
package.
It should be able to be installed using pip. It might also be required to
uninstall the default png package but I'm not sure.
Good luck!

**Comment by Mr-sh11** [comment]
If I want to hide a string of binary strings, such as' 010... 101 "how can I enter it? I want to manually extract the filter, and then what should I do to restore my ciphertext? Plz help

**Comment by dreamtimescape** [comment]
Check out the README.md file for usage examples. You can either put the
desired stuff into a file or type it out on the command line. Your binary
strings are the payload in the terminology used in the README file.
As far as decoding goes, that's what the decoder script is for. You don't
need to manually extract the filters, the script will create a file
matching the original payload.

**Comment by Mr-sh11** [comment]
fine，I have solved it by myself,thank you very much
